
name: Audodoxy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxyfile-web
          # Working directory
          working-directory: LabVIEW/vi.lib/LINXx/Firmware


      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # Build directory to deploy
          build_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
